global using Xunit;
using GraduationProject;
using GraduationProject.CocktailDB;
using GraduationProject.Controllers;
using GraduationProject.Models;
using GraduationProject.Models.CocktailDB;
using Microsoft.AspNetCore.Mvc;
using Moq;
using Moq.Protected;
using Newtonsoft.Json;
using System;
using System.Net;
using System.Net.Sockets;
using System.Reflection.Metadata;
using System.Runtime.Intrinsics.X86;
using System.Text;
using System.Text.Json;